### PR TITLE
Add paper draft

### PR DESCRIPTION
**Pull request by TomDonoghue**
A draft of the JOSE paper.

### CODE REVIEW

**Review by voytek — CHANGES_REQUESTED** [review]
This looks great, Tom! Nearly-perfect draft.

I'm not sure the best way to do this, so I just made my changes in the attached txt file.

[paper_bv.txt](https://github.com/DataScienceInPractice/Site/files/4806754/paper_bv.txt)

**Comment by TomDonoghue** [comment]
Thanks @voytek! I think I can run a diff on your text file, to see changes (or just read through it). 

For future reference, you should be able to fork this repository, and edit the file directly, and PR into this branch, or even just direct edit this branch (and those edits will get added to this PR). 
If you are logged in, this link might work for direct edits, if there's anything you want to add / change later:
https://github.com/DataScienceInPractice/Site/edit/paper/paper/paper.md

Edit: Oops, my bad, original permissions weren't set properly, which voided direct edits. I've updated you both to Owners so you have free reign on the Org. 

I forgot to mention - I didn't add any references yet. We probably don't need many, but at the end should go through and add any important ones - so if anyone has any key references to cite, please suggest them!

**Comment by ShanEllis** [comment]
Missed original note about references - as I have most/all in zotero already, I'm happy to add these on next review

**Comment by ShanEllis** [comment]
On project question (posed in email) : I think it would be helpful to provide. If I were an instructor looking at these materials, it would save me a lot of time having that template to work from (and did when I first taught the course, thanks to the two of you!) 

Also, you alluded to this, but I recently made project outline a .md file (rather than PDF from word), so  I think the effort here will be quite minimal if we decide to include.

**Comment by TomDonoghue** [comment]
Okay cool, all sounds good! 

As of right now, I'm going to:
- merge in (to this PR) edits so far from Brad's suggestions & Shannon's PR
- have a look at adding a project page to the public site (basically, linking that md file, and maybe a proposal notebook), and if it works well, adding a couple lines to the paper noting these materials are available. 
- then I can tag you both back in for another round of checks or edits, after which we should be good. 

@ShanEllis semi-related, but I'm also currently doing some clean up edits of the base 'Tutorials' repo. Just wanted to check it's fine with you to make a few changes, and push there (as in it won't break anything for you?).

**Comment by ShanEllis** [comment]
@TomDonoghue confirming updating/editing tutorials is no problem at all. Thanks for doing that! (I keep meaning to spend more time with them!)

**Comment by TomDonoghue** [comment]
As of right now, the draft has merges and updates based on comments from both of you. 

One somewhat open topic: naming. In the paper we refer to both the class version and public version as 'Data Science in Practice', and that might be a little confusing. Also, the title was a quick guess - but could very much be updated if anyone has any suggestions.

**Comment by voytek** [comment]
The current title, "Course Materials for Data Science in Practice," is fine

The only thing I could imaging doing is being a bit more descriptive. Something like, "Project-based Data Science in Python," or something like that, using more keywords.

**Comment by TomDonoghue** [comment]
I've updated the paper a bit. Since we've done a review round, and to prep the repo for submission, I'm going to merge this in now. Paper is still open for editing - just open a PR!

**Pull request merged**
